version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/backend
    environment:
      - DEBUG=True

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/frontend
    environment:
      - NODE_ENV=development

     